/**
 * internal/sidebars.ts — the five left bars of the site.
 *
 * There are exactly five, and no page defines its own:
 *
 *   mainSidebar         the whole site — every Level 2 area, flat
 *   republicanSidebar   everything under site/docs/r/
 *   democratSidebar     everything under site/docs/d/
 *   libertarianSidebar  everything under site/docs/l/
 *   socialistSidebar    everything under site/docs/s/
 *
 * The party bars are separate because those four areas are front doors onto
 * their own hierarchies. Every page under r/ gets the R bar, every page under
 * d/ gets the D bar, every page under l/ gets the L bar and every page under s/
 * gets the S bar. They are built by mapping over PARTIES so that adding a door
 * cannot forget to add its bar — a wiring convenience, not a symmetry rule.
 *
 * The bars do NOT have to match each other. Each one is autogenerated from its
 * own directory tree, so the four doors carry whatever areas they carry and are
 * expected to differ. There is no pairing between them; see internal/nav.ts.
 *
 * HOW A LEVEL 2 IS DRAWN
 * Each bar is autogenerated from the filesystem, so a new page appears in the bar
 * as soon as it exists. What the reader sees is decided by
 * src/theme/DocSidebarItem/Category, which draws a directory as ONE LINK to that
 * directory's own page:
 *
 *   * no expand chevron — nothing in the left bar opens
 *   * no Level 3 rows, so the bar never nests and never indents
 *   * clicking a Level 2 navigates to that area's Level 2 page
 *
 * The destination comes from the area's `_category_.json`:
 *
 *   { "label": "Problems", "position": 7,
 *     "link": { "type": "doc", "id": "overview" } }
 *
 * A new Level 2 area therefore needs no edit in this file — only that
 * `_category_.json` with its `link`, plus the level_2.csv row and the
 * internal/nav.ts group that the build already enforces.
 *
 * The party areas are lifted out of the root autogenerated slice by
 * `docsSidebarItemsGenerator` (internal/nav.ts), wired up in
 * docusaurus.config.ts. Without that, their pages would belong to two sidebars
 * at once and Docusaurus would have no single left bar to render for them.
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

import {MAIN_SIDEBAR_ID, PARTIES, PARTY_SIDEBAR_IDS} from './nav';

/**
 * A party edition's left bar: a way back to the parent site, then that edition's
 * own pages, autogenerated from its directory.
 */
function partySidebar(key: string) {
  return [
    {
      type: 'link' as const,
      href: '/',
      label: '← We The Citizens',
      className: 'wcSidebarParent',
    },
    {type: 'autogenerated' as const, dirName: key},
  ];
}

const sidebars: SidebarsConfig = {
  [MAIN_SIDEBAR_ID]: [{type: 'autogenerated', dirName: '.'}],

  // One per party edition, built by the same function from the same shape.
  ...Object.fromEntries(
    PARTIES.map((party) => [
      PARTY_SIDEBAR_IDS[party.key],
      partySidebar(party.key),
    ]),
  ),
};

export default sidebars;
